config/routes.rb
OpyRuby::Application.routes.draw do

    
match 'payu_step_by_step/OrderCreateRequest' => 'create_order#index'
match 'payu_step_by_step/BeforeSummaryPage' => 'before_summary_page#index'
match 'payu_step_by_step/OrderNotifyRequest' => 'order_notify_request#index'
match 'payu_step_by_step/ShippingCostRetrieveRequest' => 'shipping_cost_retrieve_request#index'
match 'payu_step_by_step/layout/page_success' => 'page_success#index'
match 'payu_step_by_step/layout/page_cancel' => 'page_cancel#index'
match 'cancel' => 'cancel_request#index'
root :to => 'main_page#index'    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/before_summary_page_controller.rb
require './lib/openpayu.rb'
require './config.rb'

class BeforeSummaryPageController < ApplicationController
	def index
		@code = params['code']
		@redirection = OpenPayU::Configuration.myUrl+ "/BeforeSummaryPage"
		@accessToken = OpenPayU::OAuth.accessTokenByCode(@code, @redirection)
	end
end

app/controllers/cancel_request_controller.rb
require './lib/openpayu.rb'
require './config.rb'
class CancelRequestController < ApplicationController
	def index
		OpenPayU::Configuration.environment
		@sessionId = params['sessionId']
		@status = params['status']
		@resp=""
		@req =""
		if (@sessionId != nil and @status != nil )then
			@result = OpenPayU::Order.retrieve(@sessionId)
		end
		if @result != nil then 
			@resp = @result.response 
		end
		if @result != nil then 
			@req = @result.request 
		end
	end
end

app/controllers/create_order_controller.rb
require './lib/openpayu.rb'
require './config.rb'

class CreateOrderController < ApplicationController
attr_accessor :docresp

  def index

  	@ipaddr = request.remote_ip

  	SpecialSession.id = OpenSSL::Digest.hexdigest("md5", rand().to_s).to_s
  	@myUrl = request.host.to_s + ":" + request.port.to_s + "/payu_step_by_step"
  	@clientIp = request.remote_ip
	

  	@shippingCost = Hash.new
  	@shippingCost = { 'CountryCode' => 'PL', 
                    	'ShipToOtherCountry' => 'true',
                    	'ShippingCostList' => {
                    	  'ShippingCost' => { 
                    	    'Type' => 'courier_0',
                          'CountryCode' => 'PL',
                          'Price' => { 'Gross' => '1220', 'Net' => '1000', 'Tax' => '22', 'TaxRate' => '22', 'CurrencyCode' => 'PLN'}
                          }
                        }
                      }                      

  	@item1 = Hash.new
  	@item1 = {  'Quantity' => 1,
                'Product' => {  
                  'Name' => 'name of test product',
                  'UnitPrice' => { 'Gross' => 10000, 'Net' => 7800, 'Tax' => 22, 'TaxRate' => '22', 'CurrencyCode' => 'PLN'}
                }
              }

  	#changed input
  	@shoppingCart = Hash.new
  	@shoppingCart = { 'GrandTotal' => 10000,
                      'CurrencyCode' => 'PLN',
                      'ShoppingCartItems' => {
                        'ShoppingCartItem' => [@item1]
                      }
                    }
                    
  	@order = Hash.new "Nonexistent key"
  	@order = {  'MerchantPosId' => OpenPayU::Configuration.merchantPosId,
              	'SessionId' => SpecialSession.id,
              	'OrderUrl' => "http://#{@myUrl}/layout/page_cancel?order=" + rand().to_s, # is url where customer will see in myaccount, and will be able to use to back to shop.
              	'OrderCreateDate' => Time.now.iso8601.to_s,
              	'OrderDescription' => OpenSSL::Digest.hexdigest("md5", rand().to_s).to_s,											
              	'MerchantAuthorizationKey' => OpenPayU::Configuration.posAuthKey ,
              	'OrderType' => 'MATERIAL', # keyword: MATERIAL or VIRTUAL 										
              	'ShoppingCart' => @shoppingCart
              }
  
  	@ocrq = {	'ReqId' =>  OpenSSL::Digest.hexdigest("md5", rand().to_s).to_s, 
                'CustomerIp' => @clientIp, # note, this should be real ip of customer retrieved from $_SERVER['REMOTE_ADDR']
                'NotifyUrl' => "http://#{@myUrl}/OrderNotifyRequest", #// url where payu service will send notification with order processing status changes
                'OrderCancelUrl' => "http://#{@myUrl}/layout/page_cancel",
                'OrderCompleteUrl' => "http://#{@myUrl}/layout/page_success",
                'Order' => @order,
                'ShippingCost' => {
                  'AvailableShippingCost' => @shippingCost,
                  'ShippingCostsUpdateUrl' => "#{@myUrl}/ShippingCostRetrieveRequest" #// this is url where payu checkout service will send shipping costs retrieve request 
                }															
              }
              
              
    @ocrs = OpenPayU::Order.create(@ocrq).response              
              
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
	def index
	end
end

app/controllers/order_notify_request_controller.rb
require './lib/openpayu.rb'
require './config.rb'
class OrderNotifyRequestController < ApplicationController

	def index
		@doc = params['DOCUMENT']
		@doc = CGI::unescapeHTML(@x)
		
		fil = File.open("Notify.txt","a")
		fil.puts("#{Time.now}\t" +@doc)
		fil.close
		
		render :text => OpenPayU::Order.consumeMessage(@doc).response
	end
end

app/controllers/page_cancel_controller.rb
class PageCancelController < ApplicationController
end

app/controllers/page_success_controller.rb
class PageSuccessController < ApplicationController
end

app/controllers/shipping_cost_retrieve_request_controller.rb
require './lib/openpayu.rb'
require './config.rb'

class ShippingCostRetrieveRequestController < ApplicationController

	def index
		@xml = params['DOCUMENT']
		@xml = CGI::unescapeHTML(@xml)	

		fil = File.open("Shipping.txt","a")
		fil.puts("#{Time.now}\t" +@xml)
		fil.close

		result = OpenPayU::Order.consumeMessage(@xml)			 
		if (result.message == 'ShippingCostRetrieveRequest') then

			arr = { 'CountryCode' => result.countryCode, 
              'ShipToOtherCountry' => 'true',
              'ShippingCostList' => {
                'ShippingCost' => [{
                  'Type' => 'recalculated_courier_0',
                  'CountryCode' => result.countryCode,
                  'Price' => {'Gross' => '1220', 'Net' => 220, 'Tax' => '22', "TaxRate" => 22, "CurrencyCode" => "PLN"}
                  },
                  {
                    'Type' => 'recalculated_courier_1',
                    'CountryCode' => result.countryCode,
                    'Price' => {'Gross' => '2440', 'Net' => 440, 'Tax' => '22', "TaxRate" => 22, "CurrencyCode" => "PLN"}
                  }]
                }
              }
		end
		
		@xml = OpenPayU.buildShippingCostRetrieveResponse(arr, result.reqId, result.countryCode)
		render :text => @xml
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/before_summary_page/index.html.erb
<h1>BEFORE SUMMARY PAGE</h1>

SessionID: <%= SpecialSession.id %>	<br />

<h2>PayU Response </h2>
Code:              <%= @code %> <br>

Token:             <%= @accessToken.accessToken %> <br>
User e-mail:       <%= @accessToken.payuUserEmail %> <br>
User ID:           <%= @accessToken.payuUserId %> <br>
Token expiration:  <%= @accessToken.expiresIn %> <br>
Refresh Token:     <%= @accessToken.refreshToken %> <br>
Success:           <%= @accessToken.success %> <br>
Error description: <%= @accessToken.error %> <br>
<br>

<h2>Next step</h2>
<a href = <%="#{OpenPayU::Configuration.summaryUrl}?sessionId=#{SpecialSession.id}&oauth_token=#{@accessToken.accessToken}"%> >NEXT </a>


<br />

app/views/cancel_request/index.html.erb

<h2> canceled </h2>
session id:  <%= SpecialSession.id %>
<br>
<h3> Request </h3>
<%= @req %>
<br>
<h3> Response </h3>
<%= @resp %>

app/views/create_order/_form.html.erb
<%= form_for(@create_order) do |f| %>
  <% if @create_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@create_order.errors.count, "error") %> prohibited this create_order from being saved:</h2>

      <ul>
      <% @create_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/create_order/edit.html.erb
<h1>Editing create_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @create_order %> |
<%= link_to 'Back', create_orders_path %>

app/views/create_order/index.html.erb
<h1>OrderCreateRequest</h1>

<span>OpenPayU endpoint for OrderCreateRequest message:<span><br/>
<b>https://<%= OpenPayU::Configuration.env %>.payu.pl/pl/standard/co/openpayu/OrderCreateRequest</b>

<h2>-&gt PayU : OrderCreateRequest</h2>
<%= @ocrq %>

<h2>&lt- PayU : OrderCreateResponse</h2>
<%= @ocrs  %>

<p>request made from ip: <%= @ipaddr %></p>

<h2>Next step (authorization in PayU)</h2>

<form action=<%="#{OpenPayU::Configuration.authUrl}"%> method="get">
	<input type="hidden" name="redirect_uri" value=<%="#{OpenPayU::Configuration.myUrl}/BeforeSummaryPage"%> >
	<input type="hidden" name="response_type" value="code">
	<input type="hidden" name="client_id" value=<%="#{OpenPayU::Configuration.clientId}"%> >		
	<input type="submit" value="next" >			
</form>

app/views/create_order/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', create_orders_path %>

app/views/create_order/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_create_order_path(@create_order) %> |
<%= link_to 'Back', create_orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PayU Step By Step for Ruby</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main_page/index.html.erb
<h1>Welcome to PayU Step By Step example for Ruby</h1>

<a href = "/payu_step_by_step/OrderCreateRequest">start payu example</a>

<br />

app/views/order_notify_request/index.html.erb
<h1>OrderNotifyRequest</h1>
	<% @y = raw @x %>
<br />

app/views/page_cancel/index.html.erb
<h1>Cancel/error</h1>

<a href = "/payu_step_by_step/OrderCreateRequest">start payu example again</a>

<h2>parameters:</h2>
<% params.each do |k,v| %>
	<br /> <%= "#{k}: #{v}" %>
	<% end %>

app/views/page_success/index.html.erb
<h1>Success</h1>

<a href = "/payu_step_by_step/OrderCreateRequest">start payu example again</a>

app/views/shipping_cost_retrieve_request/index.html.erb
<h1>ShippingCostRetrieveRequest</h1>